plugins {
    id 'com.android.application'
}

android {
    namespace 'app.cinecut.mobile'
    compileSdk 36

    defaultConfig {
        applicationId 'app.cinecut.mobile'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
